CREATE TABLE IF NOT EXISTS Users(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(30) UNIQUE NOT NULL,
  email VARCHAR(40) UNIQUE NOT NULL,
  paypal_email VARCHAR(100) UNIQUE,
  password TEXT NOT NULL,
  `role` ENUM("admin","user") DEFAULT "user",
  blanace DECIMAL(10,2) DEFAULT 0.0,
  image_url TEXT DEFAULT NULL,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Category(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(30) UNIQUE NOT NULL,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Product(
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  category_id INT NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE,
  stock INT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  description TEXT NOT NULL, 
  image_url TEXT NOT NULL,
  rating INT DEFAULT 0,
  commission_rate DECIMAL(10,2) NOT NULL,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES Category(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS Save_product(
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  product_id INT NOT NULL,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES Product(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Cart(
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  is_paid BOOLEAN default false,
  totalPrice DECIMAL(10,2),
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Cart_item(
  id INT PRIMARY KEY AUTO_INCREMENT,
  cart_id INT NOT NULL,
  product_id INT,
  quantity INT,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (cart_id) REFERENCES Cart(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES Product(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Transactions (
  id INT PRIMARY KEY AUTO_INCREMENT,

  user_id INT NOT NULL,
  card_id INT DEFAULT NULL,

  type ENUM('PAYMENT', 'WITHDRAWAL') NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  currency VARCHAR(10) DEFAULT 'USD',
  status ENUM('PENDING', 'COMPLETED', 'FAILED') DEFAULT 'PENDING',
  paypal_order_id VARCHAR(255) DEFAULT NULL,
  payout_batch_id VARCHAR(255) DEFAULT NULL,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (card_id) REFERENCES Cart(id) ON DELETE SET NULL
);

